server:
  port: 8088

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Shriyanga/config-repo.git
          clone-on-start: true
          default-label: main   # or the correct branch name
          timeout: 10
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

endpoint:
    refresh:
      enabled: true
logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
