server:
  port: 8088

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/Shriyanga/config-repo.git}
          clone-on-start: true
          default-label: main
          timeout: 10
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
